# 1. Conexao com o Banco de Dados (Docker)
spring.datasource.url=jdbc:postgresql://localhost:5432/sgcm_db
spring.datasource.username=ads_user
spring.datasource.password=ads_password
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Configuracoes do Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 3. Configuracoes de Seguranca JWT
api.security.token.secret=${JWT_SECRET:minha-chave-secreta-super-dificil-123}

# Configuracoes do Admin Master lidas do ambiente
api.security.admin.email=${ADMIN_EMAIL:admin@sgcm.com}
api.security.admin.senha=${ADMIN_PASSWORD:SenhaForte123!}

spring.jpa.open-in-view=false